import SectionHead from './SectionHead'
import { useI18n } from '../i18n'
import { FACEBOOK_URL, INSTAGRAM_URL } from '../lib/contact'
import { FacebookGlyph, InstagramGlyph } from './icons'

import cayeCaulker from '../assets/gallery/Caye Caulker.jpeg'
import sanPedro from '../assets/gallery/San Pedro.jpeg'
import sanPedro2 from '../assets/gallery/San Pedro2.jpeg'
import sanPedro3 from '../assets/gallery/San Pedro3.jpeg'
import cayo1 from '../assets/gallery/cayo1.jpeg'
import cayo2 from '../assets/gallery/cayo2.jpeg'

// Device-scaled WebP variants (generated by scripts/optimize-gallery.mjs at build)
// serve modern browsers a ~55% smaller image; the JPEG above remains the no-WebP
// fallback. Sources stay the paintable originals.
import cayeCaulkerWebP from '../assets/gallery/Caye Caulker.webp'
import sanPedroWebP from '../assets/gallery/San Pedro.webp'
import sanPedro2WebP from '../assets/gallery/San Pedro2.webp'
import sanPedro3WebP from '../assets/gallery/San Pedro3.webp'
import cayo1WebP from '../assets/gallery/cayo1.webp'
import cayo2WebP from '../assets/gallery/cayo2.webp'

/** Site photos pinned in two measured bands — portraits, then landscapes. */
interface Shot {
  src: string
  webp: string
  /** Location proper noun, derived verbatim from the source file name. */
  label: string
}

const PORTRAITS: Shot[] = [
  { src: sanPedro, webp: sanPedroWebP, label: 'San Pedro' },
  { src: sanPedro2, webp: sanPedro2WebP, label: 'San Pedro' },
  { src: cayo2, webp: cayo2WebP, label: 'Cayo' },
]
const LANDSCAPES: Shot[] = [
  { src: cayeCaulker, webp: cayeCaulkerWebP, label: 'Caye Caulker' },
  { src: cayo1, webp: cayo1WebP, label: 'Cayo' },
  { src: sanPedro3, webp: sanPedro3WebP, label: 'San Pedro' },
]

/** One framed photo with a survey tick and a mono field-note caption. */
function Plate({ shot, ratio }: { shot: Shot; ratio: string }) {
  return (
    <figure data-reveal>
      <div
        className={`relative overflow-hidden border border-ink/25 bg-concrete-100 ${ratio}`}
      >
        <span aria-hidden="true" className="absolute left-2.5 top-2.5 z-10 h-3 w-3 border border-rebar bg-paper/60" />
        <picture>
          <source srcSet={shot.webp} type="image/webp" />
          <img
            src={shot.src}
            alt={shot.label}
            loading="lazy"
            decoding="async"
            className="h-full w-full object-cover"
          />
        </picture>
      </div>
      <figcaption className="mt-3 flex items-center gap-3 border-t border-ink/15 pt-2.5">
        <span
          aria-hidden="true"
          className="relative h-[13px] w-[13px] shrink-0 text-rebar-dark"
        >
          <span className="absolute left-1/2 top-0 h-full w-px -translate-x-1/2 bg-current" />
          <span className="absolute top-1/2 left-0 w-full h-px -translate-y-1/2 bg-current" />
        </span>
        <span className="plan-label !text-[11px]">{shot.label}</span>
      </figcaption>
    </figure>
  )
}

/** Gallery — site photography pinned to a light sheet before the closing CTA. */
export default function Gallery() {
  const { t } = useI18n()
  return (
    <section id="gallery" className="bg-concrete-100 text-ink">
      <div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 md:py-28">
        <SectionHead heading={t.gallery.heading} lede={t.gallery.lede} tag="SECTION 04 · SITE" />

        {/* portraits */}
        <div className="mt-14 grid gap-5 sm:grid-cols-2 sm:gap-6 lg:grid-cols-3">
          {PORTRAITS.map((shot, i) => (
            <Plate key={i} shot={shot} ratio="aspect-[3/4]" />
          ))}
        </div>

        {/* landscapes */}
        <div className="mt-5 grid gap-5 sm:grid-cols-2 sm:gap-6 lg:grid-cols-3">
          {LANDSCAPES.map((shot, i) => (
            <Plate key={i} shot={shot} ratio="aspect-[4/3]" />
          ))}
        </div>

        {/* follow-on socials — "Explore more on:" leading the official FB/IG glyphs */}
        <div
          data-reveal
          className="mt-14 flex flex-wrap items-center justify-center gap-x-4 gap-y-4 border-t border-ink/15 pt-8"
        >
          <span className="plan-label !text-[11px] !normal-case">{t.gallery.exploreMore}</span>
          <span className="flex items-center gap-2.5">
            <a
              href={FACEBOOK_URL}
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Facebook"
              className="grid h-10 w-10 place-items-center border border-ink/20 text-ink transition-colors hover:border-rebar hover:text-rebar"
            >
              <FacebookGlyph size={20} />
            </a>
            <a
              href={INSTAGRAM_URL}
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Instagram"
              className="grid h-10 w-10 place-items-center border border-ink/20 text-ink transition-colors hover:border-rebar hover:text-rebar"
            >
              <InstagramGlyph size={20} />
            </a>
          </span>
        </div>
      </div>
    </section>
  )
}